using Godot;
using Shuabao.Core;
using System.Text.Json;
using GFile = Godot.FileAccess;
namespace Shuabao.Game;

public partial class Main : Control
{
    private GameEngine _engine = null!; private Catalog _catalog = null!; private AssetStore _assets = null!; private Theme _theme = null!;
    private VBoxContainer _body = null!; private Label _resources = null!, _notice = null!, _count = null!; private ScrollContainer _scroll = null!; private Window? _dialog; private string? _offerId; private System.IO.FileStream? _lock;
    private string _page = "battle", _hero = "", _role = "all", _craftSlot = "weapon", _craftSet = "破军", _manualAction = "auto", _manualTarget = ""; private int _stage = 1, _region, _speed = 2, _dispatchStage = 1; private bool _paused, _autoNext, _sound, _smoke; private double _battleTime, _clockTime; private string _savePath = "";
    private readonly Color _text = new("deded0"), _muted = new("8a9c98"), _gold = new("cdb48a"), _jade = new("96baa5");
    private static long Now => DateTimeOffset.UtcNow.ToUnixTimeMilliseconds();
    private GameState S => _engine.State;
    public override void _Ready()
    {
        try
        {
            _smoke = OS.GetCmdlineUserArgs().Contains("--smoke-test"); _assets = new(); _theme = CreateTheme(); Theme = _theme; _catalog = Catalog.Load(GFile.GetFileAsString("res://Data/catalog.json"));
            _savePath = ProjectSettings.GlobalizePath(_smoke ? "user://smoke/game.save.json" : "user://game.save.json"); System.IO.Directory.CreateDirectory(System.IO.Path.GetDirectoryName(_savePath)!);
            _lock = new System.IO.FileStream(_savePath + ".lock", System.IO.FileMode.OpenOrCreate, System.IO.FileAccess.ReadWrite, System.IO.FileShare.None);
            var loaded = _smoke ? (State: (GameState?)null, Recovered: false) : SaveCodec.Read(_catalog, _savePath);
            _engine = new(_catalog, loaded.State ?? Model.New(_catalog, _smoke ? 3 : Now, Now), state => SaveCodec.WriteAtomic(_savePath, state)); if (loaded.State == null) SaveCodec.WriteAtomic(_savePath, S);
            _hero = S.Heroes.Keys.First(); _stage = Math.Min(120, Rules.MaxClear(S) + 1); _region = (_stage - 1) / 30; _dispatchStage = Math.Max(1, Rules.MaxClear(S));
            BuildShell(); var offline = (ClockResult?)_engine.Execute(new("clock"), Now); Render();
            if (loaded.Recovered) Notice("主存档异常，已恢复上一版备份。"); else if (offline?.Elapsed > 300000) Notice($"离线推进{offline.Elapsed / 60000}分钟，完成{offline.Cycles}轮委托。收益已入账。"); else Notice("掌心洞天已展开。招贤、组队，踏上归途。");
            if (_smoke) CallDeferred(nameof(Smoke));
        }
        catch (Exception e) { ShowFatal(e); }
    }
    public override void _ExitTree() { _lock?.Dispose(); }
    public override void _Process(double delta) { if (_engine == null || _body == null || _smoke) return; _clockTime += delta; _battleTime += delta; if (_clockTime >= 15) { _clockTime = 0; Try(new("clock"), false); UpdateResources(); } if (S.Encounter != null && !_paused && _dialog == null && _battleTime >= .9 / _speed) { _battleTime = 0; StepBattle(); } }
    private Theme CreateTheme() { var t = new Theme { DefaultFont = _assets.Font(), DefaultFontSize = 15 }; t.SetColor("font_color", "Label", _text); foreach (string state in new[] { "normal", "hover", "pressed", "focus", "disabled" }) { var style = Box(state == "hover" ? "304c43" : state == "pressed" ? "48543d" : "213638", state == "focus" ? "cdb48a" : "41584f", 6, 10); t.SetStylebox(state, "Button", style); t.SetStylebox(state, "OptionButton", style); } t.SetStylebox("panel", "PanelContainer", Box("182a2d", "304744", 8, 20)); t.SetStylebox("panel", "PopupMenu", Box("203535", "496052", 6, 12)); t.SetColor("font_color", "Button", _text); t.SetColor("font_hover_color", "Button", _gold); t.SetColor("font_disabled_color", "Button", new Color("63766b")); t.SetStylebox("background", "ProgressBar", Box("102025", "102025", 3, 0)); t.SetStylebox("fill", "ProgressBar", Box("91ae87", "91ae87", 3, 0)); return t; }
    private static StyleBoxFlat Box(string fill, string border, int radius, int padding) { return new() { BgColor = new Color(fill), BorderColor = new Color(border), BorderWidthLeft = 1, BorderWidthRight = 1, BorderWidthTop = 1, BorderWidthBottom = 1, CornerRadiusTopLeft = radius, CornerRadiusTopRight = radius, CornerRadiusBottomLeft = radius, CornerRadiusBottomRight = radius, ContentMarginLeft = padding, ContentMarginRight = padding, ContentMarginTop = padding, ContentMarginBottom = padding }; }
    private static VBoxContainer VBox(Node parent, int gap = 12) { var box = new VBoxContainer { SizeFlagsHorizontal = SizeFlags.ExpandFill }; box.AddThemeConstantOverride("separation", gap); parent.AddChild(box); return box; }
    private static HBoxContainer Row(Node parent, int gap = 12) { var row = new HBoxContainer { SizeFlagsHorizontal = SizeFlags.ExpandFill }; row.AddThemeConstantOverride("separation", gap); parent.AddChild(row); return row; }
    private VBoxContainer Panel(Node parent, int width = 0) { var panel = new PanelContainer { SizeFlagsHorizontal = SizeFlags.ExpandFill, CustomMinimumSize = new Vector2(width, 0) }; parent.AddChild(panel); return VBox(panel); }
    private Label Text(Node parent, string text, int size = 15, Color? color = null, bool wrap = true) { var label = new Label { Text = text, SizeFlagsHorizontal = SizeFlags.ExpandFill, AutowrapMode = wrap ? TextServer.AutowrapMode.WordSmart : TextServer.AutowrapMode.Off }; label.AddThemeFontSizeOverride("font_size", size); label.AddThemeColorOverride("font_color", color ?? _text); parent.AddChild(label); return label; }
    private Button Button(Node parent, string text, Action callback, bool primary = false, bool disabled = false, string? tag = null) { var b = new Button { Text = text, Disabled = disabled, CustomMinimumSize = new Vector2(0, 38) }; if (primary) { b.AddThemeStyleboxOverride("normal", Box("bca981", "dcc497", 5, 10)); b.AddThemeColorOverride("font_color", new Color("182b26")); } b.Pressed += callback; if (tag != null) b.SetMeta("test_tag", tag); parent.AddChild(b); return b; }
    private OptionButton Select(Node parent, IEnumerable<(string Id, string Name)> options, string current, Action<string> changed) { var b = new OptionButton { CustomMinimumSize = new Vector2(155, 38), SizeFlagsHorizontal = SizeFlags.ExpandFill, FitToLongestItem = false }; var values = options.ToList(); for (int i = 0; i < values.Count; i++) { b.AddItem(values[i].Name); if (values[i].Id == current) b.Select(i); } b.ItemSelected += i => changed(values[(int)i].Id); parent.AddChild(b); return b; }
    private TextureRect Image(Node parent, string asset, int width, int height) { var t = new TextureRect { Texture = _assets.Texture(asset), CustomMinimumSize = new Vector2(width, height), ExpandMode = TextureRect.ExpandModeEnum.IgnoreSize, StretchMode = TextureRect.StretchModeEnum.KeepAspectCentered, MouseFilter = MouseFilterEnum.Ignore }; parent.AddChild(t); return t; }
    private void BuildShell() { var margin = new MarginContainer(); margin.SetAnchorsAndOffsetsPreset(LayoutPreset.FullRect); AddChild(margin); var layout = Row(margin, 0); var sidebar = Panel(layout, 210); sidebar.SizeFlagsHorizontal = SizeFlags.ShrinkBegin; Image(sidebar, "icon.sect", 55, 55); Text(sidebar, "异界刷宝录", 25, _gold); Text(sidebar, "GODOT / 原生单机版", 11, _muted); foreach (var (id, title, sub) in new[] { ("battle", "征途", "关卡与战斗"), ("heroes", "名将", "养成与阵容"), ("summon", "招贤", "抽取与许愿"), ("bag", "宝库", "装备与锻造"), ("sect", "洞天", "建设与委托"), ("story", "绘卷", "剧情与历练"), ("settings", "设置", "存档与素材") }) { var key = id; var b = Button(sidebar, $"{title}   ·   {sub}", () => { _page = key; CloseDialog(); Render(); }, tag: "nav-" + key); b.Alignment = HorizontalAlignment.Left; } var spacer = new Control { SizeFlagsVertical = SizeFlags.ExpandFill }; sidebar.AddChild(spacer); _count = Text(sidebar, "", 15, _gold); Text(sidebar, "遍寻古今英杰\n重开现世之门", 12, _muted); var right = VBox(layout, 0); var top = Panel(right); _resources = Text(top, "", 16, _gold); _scroll = new ScrollContainer { SizeFlagsVertical = SizeFlags.ExpandFill, SizeFlagsHorizontal = SizeFlags.ExpandFill, HorizontalScrollMode = ScrollContainer.ScrollMode.Disabled }; right.AddChild(_scroll); var m = new MarginContainer { SizeFlagsHorizontal = SizeFlags.ExpandFill }; foreach (var side in new[] { "left", "right", "top", "bottom" }) m.AddThemeConstantOverride("margin_" + side, 25); _scroll.AddChild(m); _body = VBox(m, 20); _notice = Text(right, "", 13, _jade); _notice.CustomMinimumSize = new Vector2(0, 36); }
    private void UpdateResources() { if (_resources == null) return; _resources.Text = $"招募券 {S.Resources["ticket"]:N0}     铜钱 {S.Resources["gold"]:N0}     矿石 {S.Resources["ore"]:N0}     灵草 {S.Resources["herb"]:N0}     修为 {S.Resources["xp"]:N0}     残忆 {S.Resources["echo"]:N0}"; _count.Text = $"归途名册   {S.Heroes.Count} / 96"; }
    private void Notice(string text) { if (_notice != null) _notice.Text = "  " + text; }
    private bool Try(Command cmd, bool render = true) { try { var result = _engine.Execute(cmd, Now); if (cmd.Type == "choose") { CloseDialog(); Sound("draw"); } if (render) Render(); if (cmd.Type is not ("step" or "clock")) Notice(result switch { ChoiceResult r => r.Item != null ? $"{r.Name}已收入宝库" : $"{_catalog.ById[r.Id].Name} · {(r.IsNew ? "新人加入" : "培养碎片已入账")}", int n when cmd.Type == "trial" => $"历练完成，专属片 +{n}", _ => "操作完成，进度已保存。" }); return true; } catch (Exception e) { Notice(e.Message); return false; } }
    private void Render() { int position = _scroll.ScrollVertical; foreach (var child in _body.GetChildren()) { _body.RemoveChild(child); child.QueueFree(); } UpdateResources(); switch (_page) { case "battle": Expedition(); break; case "heroes": Heroes(); break; case "summon": Summon(); break; case "bag": Bag(); break; case "sect": Sect(); break; case "story": StoryPage(); break; case "settings": Settings(); break; } _scroll.SetDeferred(ScrollContainer.PropertyName.ScrollVertical, position); if (S.Pending != null && _offerId != S.Pending.Id) OfferDialog(); }
    private void Heading(string kicker, string title, string subtitle) { Text(_body, kicker, 12, _gold); Text(_body, title, 30); Text(_body, subtitle, 14, _muted); }
    private void HeroCard(Node parent, HeroDef h, Action callback, int width = 145) { var button = new Button { CustomMinimumSize = new Vector2(width, 225), SizeFlagsHorizontal = SizeFlags.ExpandFill }; parent.AddChild(button); button.Pressed += callback; var v = VBox(button, 4); v.MouseFilter = MouseFilterEnum.Ignore; v.SetAnchorsAndOffsetsPreset(LayoutPreset.FullRect); Image(v, h.Asset, width - 18, 145); var name = Text(v, h.Name, 20, _text, false); name.HorizontalAlignment = HorizontalAlignment.Center; var info = Text(v, $"{h.Rarity} · {Catalog.Roles[h.Role]}", 12, _gold, false); info.HorizontalAlignment = HorizontalAlignment.Center; var own = S.Heroes.GetValueOrDefault(h.Id); var lv = Text(v, own == null ? h.Story ? "剧情专属" : "尚未结识" : $"{Catalog.Ranks[own.Rank]} · Lv.{own.Level}", 11, _muted, false); lv.HorizontalAlignment = HorizontalAlignment.Center; foreach (var node in v.GetChildren().OfType<Control>()) node.MouseFilter = MouseFilterEnum.Ignore; }
    private void Formation(Node parent) { var grid = new GridContainer { Columns = 3, SizeFlagsHorizontal = SizeFlags.ExpandFill }; parent.AddChild(grid); for (int i = 0; i < 6; i++) { int slot = i; var id = S.Formation[i]; Button(grid, $"{(i < 3 ? "前" : "后")}排 {i % 3 + 1}\n{(id == null ? "+ 选择名将" : _catalog.ById[id].Name + " Lv." + S.Heroes[id].Level)}", () => FormationDialog(slot), tag: $"slot-{slot}").SizeFlagsHorizontal = SizeFlags.ExpandFill; } }
    private void Expedition() { if (S.Encounter != null) { BattlePage(); return; } Heading("EXPEDITION / 山河征途", "一卷山河，待君开拓", "每关三波；普通胜利10券，Boss胜利共30券。重复关卡仍有奖励。"); var banner = Panel(_body); Image(banner, $"background.region.{(_stage - 1) / 30}", 800, 170); Text(banner, Catalog.Regions[(_stage - 1) / 30], 28, _gold); var row = Row(_body); var stages = Panel(row, 540); Select(stages, Enumerable.Range(0, 4).Select(i => (i.ToString(), Catalog.Regions[i])), _region.ToString(), v => { _region = int.Parse(v); Render(); }); var grid = new GridContainer { Columns = 10, SizeFlagsHorizontal = SizeFlags.ExpandFill }; stages.AddChild(grid); foreach (var def in _catalog.Stages.Where(x => x.Region == _region)) { int n = def.Id; Button(grid, $"{n:00}\n{(def.Boss ? "首领" : S.Cleared.Contains(n) ? "已通" : "关卡")}", () => { _stage = n; Render(); }, n == _stage, n > Rules.MaxClear(S) + 1).SizeFlagsHorizontal = SizeFlags.ExpandFill; } var stage = _catalog.Stages[_stage - 1]; Text(stages, $"第 {_stage} 关 · {stage.Name}", 22); Text(stages, stage.Boss ? "第三波蓄力全体伤害：控制打断，或守御治疗承受。" : "前排保护后排。尝试搭配守御、医者和远袭名将。", 13, _muted); var actions = Row(stages); Button(actions, "出征 →", () => { _paused = false; Try(new("battle", Number: _stage)); }, true, tag: "start-battle"); Button(actions, "派遣挂机", () => Try(new("dispatch", Number: _stage)), disabled: !S.Cleared.Contains(_stage)); var formation = Panel(row, 330); Text(formation, "出战阵容", 21); Formation(formation); Text(formation, "同职责2人：守御生命+10%、强攻攻击+10%、谋略法攻+10%、远袭速度+10。", 12, _muted); Button(formation, "培养与装备", () => { _page = "heroes"; Render(); }); DispatchPanel(_body); }
    private void BattlePage()
    {
        var b = S.Encounter!; Heading($"ENCOUNTER / 第 {b.Stage} 关", _catalog.Stages[b.Stage - 1].Name, $"第 {b.Wave} / 3 波 · 第 {b.Round} 回合 · 跨波继承生命、灵力、体力与冷却"); var arena = Panel(_body); var sides = Row(arena, 20); foreach (string side in new[] { "ally", "enemy" }) { var area = VBox(sides); Text(area, side == "ally" ? "我方 · 洞天名将" : "敌方 · 异境守卫", 20, side == "ally" ? _jade : _gold); var grid = new GridContainer { Columns = 2, SizeFlagsHorizontal = SizeFlags.ExpandFill }; area.AddChild(grid); foreach (int slot in side == "ally" ? new[] { 3, 0, 4, 1, 5, 2 } : new[] { 0, 3, 1, 4, 2, 5 }) { var unit = b.Units.Find(x => x.Side == side && x.Slot == slot); var panel = Panel(grid); panel.CustomMinimumSize = new Vector2(210, 125); if (unit == null) { Text(panel, "—", 20, _muted); continue; } var row = Row(panel); Image(row, side == "ally" ? _catalog.ById[unit.Source!].Asset : unit.Boss ? "enemy.boss" : "enemy.soldier", 60, 100); var v = VBox(row, 3); Text(v, $"{unit.Name}{(unit.Hp == 0 ? " · 倒下" : "")}", 18); Text(v, $"{Catalog.Roles[unit.Role]} · {(unit.Slot < 3 ? "前排" : "后排")}", 10, _muted); v.AddChild(new ProgressBar { MaxValue = unit.Stats.Hp, Value = unit.Hp, ShowPercentage = false, CustomMinimumSize = new Vector2(110, 8) }); Text(v, $"{unit.Hp}/{unit.Stats.Hp}   灵 {unit.Mp}", 11, _muted); Text(v, $"{(unit.Charge ? "蓄力！ " : "")}{(unit.Stun > 0 ? "眩晕 " : "")}{(unit.Burn > 0 ? "灼烧 " : "")}{(unit.Shield > 0 ? "护盾 " : "")}{(unit.Mark > 0 ? "破绽" : "")}", 10, _gold); if (unit.Hp == 0) panel.Modulate = new Color(1, 1, 1, .35f); } }
        var controls = Row(_body); Button(controls, _paused ? "继续自动" : "暂停", () => { _paused = !_paused; Render(); }, true, tag: "pause-battle"); Button(controls, "推进一行动", () => { _paused = true; StepBattle(); }); Select(controls, new[] { ("1", "1× 演出"), ("2", "2× 演出"), ("4", "4× 演出"), ("8", "8× 演出") }, _speed.ToString(), v => _speed = int.Parse(v)); var auto = new CheckButton { Text = "胜利后继续下一关", ButtonPressed = _autoNext }; auto.Toggled += v => _autoNext = v; controls.AddChild(auto); Button(controls, "撤回洞天", () => Try(new("retreat")));
        var bottom = Row(_body); var tactical = Panel(bottom); Text(tactical, "战术指令", 20); Select(tactical, new[] { ("auto", "使用职责技能"), ("attack", "普通攻击"), ("rest", "调息恢复") }, _manualAction, v => _manualAction = v); Select(tactical, new[] { ("", "自动索敌") }.Concat(b.Units.Where(u => u.Side == "enemy" && u.Hp > 0).Select(u => (u.Id, u.Name))), _manualTarget, v => _manualTarget = v); Button(tactical, "交给下一位我方角色执行", Manual, disabled: !_paused); var log = Panel(bottom); Text(log, "战斗记录", 20); foreach (var line in b.Log.TakeLast(6).Reverse()) Text(log, line, 12, _muted);
    }
    private void StepBattle(string? action = null) { if (S.Pending != null || S.Encounter == null) return; if (S.Encounter.Status == "active" && !Try(new("step", Action: action, Other: _manualTarget), false)) { _paused = true; return; } if (S.Encounter!.Status != "active") { Reward reward; try { reward = (Reward)_engine.Execute(new("settle"), Now)!; } catch (Exception e) { _paused = true; Notice(e.Message); return; } _stage = Math.Min(120, reward.Stage + (reward.Defeat ? 0 : 1)); _region = (_stage - 1) / 30; if (_autoNext && !reward.Defeat && reward.Stage < 120 && S.Pending == null && !_catalog.Heroes.Any(h => h.Story && h.Unlock <= Rules.MaxClear(S) && !S.Story.Contains(h.Id))) { Try(new("battle", Number: _stage), false); } else { _autoNext = false; Render(); if (S.Pending == null) ShowDialog(reward.Defeat ? "整顿队伍，再战山河" : "三波告捷", v => { Text(v, reward.Defeat ? "队伍安全返回，角色与装备无损。尝试培养、换装和调整前后排。" : $"第{reward.Stage}关胜利\n招募券 +{reward.Tickets}\n修为 +{reward.Xp}\n装备 {reward.Items.Count} 件", 19); Button(v, "返回洞天", CloseDialog, true); }); } if (!reward.Defeat) Sound("win"); } if (_page == "battle") Render(); }
    private void Manual() { for (int i = 0; i < 20 && S.Encounter?.Status == "active"; i++) { var b = S.Encounter; var next = b.Queue.Count > 0 ? b.Units.Find(u => u.Id == b.Queue[0]) : b.Units.Where(u => u.Hp > 0).OrderByDescending(u => u.Stats.Speed).ThenBy(u => u.Id, StringComparer.Ordinal).First(); if (next?.Side == "ally" && next.Hp > 0) { StepBattle(_manualAction); break; } StepBattle(); } }
    private void Heroes()
    {
        Heading("ROSTER / 名将录", "古今英杰，同归一途", "每位人物只有一个永久身份。碎片用于突破，阵容预设不占用岗位。"); if (!S.Heroes.ContainsKey(_hero)) _hero = S.Heroes.Keys.First(); var row = Row(_body); var list = VBox(row); Select(list, new[] { ("all", "全部职责") }.Concat(Catalog.Roles.Select(x => (x.Key, x.Value))), _role, v => { _role = v; Render(); }); var grid = new GridContainer { Columns = 4, SizeFlagsHorizontal = SizeFlags.ExpandFill }; list.AddChild(grid); foreach (var h in _catalog.Heroes.Where(h => S.Heroes.ContainsKey(h.Id) && (_role == "all" || h.Role == _role))) HeroCard(grid, h, () => { _hero = h.Id; Render(); }, 130); var team = Panel(list); Text(team, "六人阵容", 20); Formation(team); var presets = Row(team); Button(presets, "保存当前预设", () => Try(new("preset-save"))); for (int i = 0; i < S.Presets.Count; i++) { int index = i; Button(presets, S.Presets[i].Name, () => Try(new("preset-load", Index: index))); }
        var detail = Panel(row, 340); detail.SizeFlagsHorizontal = SizeFlags.ShrinkEnd; var def = _catalog.ById[_hero]; var own = S.Heroes[_hero]; var st = Model.Compute(_catalog, S, _hero); Image(detail, def.Asset, 280, 225); Text(detail, def.Name, 29, _gold); Text(detail, $"{def.Rarity} · {Catalog.Roles[def.Role]} · {Catalog.Ranks[own.Rank]} Lv.{own.Level}/{Catalog.Caps[own.Rank]}", 14); Text(detail, $"生命 {st.Hp}   攻击 {st.Atk}   法攻 {st.Magic}\n防御 {st.Def}   法防 {st.Mdef}   速度 {st.Speed}", 15); Text(detail, string.Join("  ", Catalog.Attrs.Select((a, i) => $"{a}{def.Attrs[i]}")), 12, _muted); Text(detail, Catalog.Skills[def.Role].Name, 20, _jade); Text(detail, Catalog.Skills[def.Role].Text, 13, _muted); var grow = Row(detail); Button(grow, "升1级", () => Try(new("train", _hero, 1)), true); Button(grow, "升10级", () => Try(new("train", _hero, 10))); Button(grow, "突破", () => Try(new("promote", _hero)), disabled: own.Rank == 5); Text(detail, $"本人片 {S.Fragments.GetValueOrDefault(_hero)} · 熟练度 {own.Mastery}/100\n" + (own.Rank < 5 ? $"下阶需满{Catalog.Caps[own.Rank]}级、{Catalog.Costs[own.Rank]}片、通关{Catalog.Gates[own.Rank]}" : "六阶已圆满"), 12, _muted); foreach (var slot in Catalog.Slots) { var eq = own.Equipment.GetValueOrDefault(slot); var item = S.Items.Find(x => x.Id == eq); var line = Row(detail); Text(line, $"{Catalog.SlotNames[slot]} · {(item == null ? "空" : item.Name + " +" + item.Enhance)}", 13); if (item != null) Button(line, "卸下", () => Try(new("unequip", _hero, Other: slot))); }
        Text(detail, "公共战技 · 最多三项", 19); foreach (var (id, skill) in Catalog.PublicSkills) { string key = id; Button(detail, $"{(own.Skills.Contains(id) ? "✓ " : "")}{skill.Name} · {skill.Text}", () => Try(new("learn", _hero, Other: key))); }
        Text(detail, "藏经阁开放后可装入，每次200铜钱；最多1被动、1反击。", 11, _muted);
    }
    private void Summon() { _region = Math.Min(_region, Math.Min(3, Rules.MaxClear(S) / 30)); Heading("SUMMON / 招贤台", "十契一席，故人可期", "前九抽随机，第十抽三选一。有缺员时至少一位新人可选；满池后定向30片。"); Select(_body, Enumerable.Range(0, Math.Min(4, Rules.MaxClear(S) / 30 + 1)).Select(i => (i.ToString(), Catalog.Regions[i])), _region.ToString(), v => { _region = int.Parse(v); Render(); }); var banner = Panel(_body); var row = Row(banner); var copy = VBox(row); Text(copy, "以契为引，与英杰重逢", 30, _gold); Text(copy, "没有每日任务，没有限时卡池。\n稀有SSR与UR的角色及碎片只来自剧情。", 16, _muted); var buttons = Row(copy); Button(buttons, $"招贤 {10 - S.Draws[_region] % 10} 次", () => Try(new("draw", Number: _region)), true, tag: "draw-pack"); Button(buttons, "单次招贤", () => Try(new("draw", Number: _region, Single: true))); Text(copy, $"持有 {S.Resources["ticket"]} 券 · 本轮 {S.Draws[_region] % 10}/10", 14, _muted); Image(row, "building.summon", 250, 190); var eligible = _catalog.Heroes.Where(h => h.Region == _region && !h.Story).ToList(); Select(_body, eligible.Select(h => (h.Id, h.Name + (S.Heroes.ContainsKey(h.Id) ? " · 培养" : " · 未拥有"))), S.Wishlist[_region] ?? eligible[0].Id, v => Try(new("wish", v, _region))); Text(_body, "许愿只影响三选一优先项。前九抽：整卡60% / 20碎片40%；N15%、R45%、SR35%、普通SSR5%。", 12, _muted); var grid = new GridContainer { Columns = 6, SizeFlagsHorizontal = SizeFlags.ExpandFill }; _body.AddChild(grid); foreach (var h in eligible) HeroCard(grid, h, () => { Try(new("wish", h.Id, _region)); Notice("已许愿：" + h.Name); }); }
    private void Bag() { Heading("TREASURY / 宗门宝库", "一器一策，百战成锋", "四部位、两件同名套装。强化必成，最高+10；已装备与锁定装备不能分解。"); Select(_body, S.Heroes.Keys.Select(id => (id, "穿戴给 " + _catalog.ById[id].Name)), _hero, v => _hero = v); var craft = Panel(_body); Text(craft, "定向锻造 · 50矿石 + 350铜钱", 20); var row = Row(craft); Select(row, Catalog.Slots.Select(id => (id, Catalog.SlotNames[id])), _craftSlot, v => _craftSlot = v); Select(row, Catalog.Sets.Select(x => (x, x)), _craftSet, v => _craftSet = v); Button(row, "锻造", () => Try(new("craft", _craftSlot, Other: _craftSet)), true, !S.Buildings.ContainsKey("forge")); Text(craft, "两件套：破军攻击+15% / 长生生命+15% / 玄策法攻+15% / 流风速度+15", 12, _muted); if (S.Inbox.Count > 0) Button(_body, $"领取溢出保管 {S.Inbox.Count} 件", () => Try(new("inbox"))); Text(_body, $"装备 {S.Items.Count}/500", 16, _gold); var grid = new GridContainer { Columns = 3, SizeFlagsHorizontal = SizeFlags.ExpandFill }; _body.AddChild(grid); foreach (var it in S.Items.AsEnumerable().Reverse()) { var panel = Panel(grid); var title = Row(panel); Image(title, "icon." + it.Slot, 50, 50); Text(title, $"{it.Name} +{it.Enhance}", 19, _gold); Text(panel, $"{new[] { "", "普通", "精良", "史诗" }[it.Quality]} · 装等{it.Level} · 主属性 {Rules.Round(it.Power * (1 + it.Enhance * .12))}\n词缀 {it.Affix.Key} +{it.Affix.Value}", 13, _muted); var owner = S.Heroes.Values.FirstOrDefault(h => h.Equipment.ContainsValue(it.Id)); Text(panel, owner == null ? "背包中" : "持有者：" + _catalog.ById[owner.Id].Name, 12, _jade); var actions = Row(panel); Button(actions, "穿戴", () => Try(new("equip", _hero, Other: it.Id)), true); Button(actions, "强化", () => Try(new("enhance", it.Id))); Button(actions, it.Locked ? "解锁" : "锁定", () => Try(new("lock", it.Id))); Button(panel, "分解", () => Try(new("dismantle", it.Id)), disabled: owner != null || it.Locked); } if (S.Items.Count == 0) Text(_body, "宝库尚待充盈。通关获得装备，第5关开放定向锻造。", 20, _muted); }
    private void DispatchPanel(Node parent) { if (S.Dispatch is not { } d) return; var panel = Panel(parent); Text(panel, $"第 {d.Stage} 关委托 · {(d.Paused ? "已暂停" : "执行中")}", 20, _jade); Text(panel, $"当前 {d.Elapsed / 60000}/{d.CycleMs / 60000} 分钟 · 已完成 {d.Index} 轮\n每小时60券；离线最多48小时。", 13, _muted); var row = Row(panel); if (d.Paused) Button(row, "恢复委托", () => Try(new("dispatch-resume"))); Button(row, "结束委托", () => Try(new("dispatch-stop"))); }
    private void Sect() { Heading("SANCTUM / 随身洞天", "方寸之间，自成山河", "首通解锁建筑，三级即时升级。无人也产出，派驻翻倍；出战自动离岗。"); DispatchPanel(_body); var dispatch = Panel(_body); Text(dispatch, "已通关委托", 20); var row = Row(dispatch); var cleared = S.Cleared.Order().ToList(); if (cleared.Count > 0) { if (!cleared.Contains(_dispatchStage)) _dispatchStage = cleared[^1]; Select(row, cleared.Select(n => (n.ToString(), $"第{n}关" + (n % 10 == 0 ? " · Boss" : ""))), _dispatchStage.ToString(), v => _dispatchStage = int.Parse(v)); Button(row, "开始委托", () => Try(new("dispatch", Number: _dispatchStage)), true, S.Dispatch != null || S.Encounter != null); } else Text(dispatch, "先完成一关，即可开启委托。", 14, _muted); Text(dispatch, "普通关10分钟/10券，Boss30分钟/30券。主动挑战暂停原委托并保留进度，返回后手动恢复。", 13, _muted); var grid = new GridContainer { Columns = 3, SizeFlagsHorizontal = SizeFlags.ExpandFill }; _body.AddChild(grid); foreach (var b in _catalog.Buildings) { var panel = Panel(grid); int level = S.Buildings.GetValueOrDefault(b.Id); Image(panel, b.Asset, 240, 145); Text(panel, b.Name + (level > 0 ? $"   Lv.{level}/3" : $"   第{b.Unlock}关开放"), 20, _gold); Text(panel, b.Desc, 13, _muted); if (level > 0) { Text(panel, b.Id == "summon" ? "招贤契约永久开放" : $"每2分钟产出 {level * (b.Resource == "gold" ? 45 : b.Resource == "xp" ? 35 : 4)} {b.Resource}，派驻×2", 12, _jade); Select(panel, new[] { ("", "无人值守") }.Concat(S.Heroes.Keys.Select(id => (id, _catalog.ById[id].Name))), S.Workers.GetValueOrDefault(b.Id) ?? "", v => Try(new("worker", b.Id, Other: v == "" ? null : v))); Button(panel, level >= 3 ? "已满级" : $"升级 · {800 * level}铜钱 / {60 * level}矿石", () => Try(new("building", b.Id)), disabled: level >= 3); } else panel.Modulate = new Color(1, 1, 1, .4f); } }
    private void StoryPage() { Heading("CHRONICLE / 异界绘卷", "故人入卷，归途渐明", "主线名册96人全部结识，并战胜第120关归墟之主，返回现世。"); var prologue = Panel(_body); Text(prologue, "你醒来时，掌心多了一方洞天。", 26, _gold); Text(prologue, "历史的山河真实得触手可及。散落在异界的英杰，都是世界碎裂前的回响。与他们结缘，让所有名字重新聚拢；然后去归墟，打破最后的封印。", 15, _muted); Text(prologue, $"名册 {S.Heroes.Count}/96     剧情结缘 {S.Story.Count}/24     终战 {(S.Cleared.Contains(120) ? "已胜利" : "等待挑战")}", 17, _jade); if (S.Ending) Button(prologue, "重温返回现实结局", EndingDialog, true); var grid = new GridContainer { Columns = 3, SizeFlagsHorizontal = SizeFlags.ExpandFill }; _body.AddChild(grid); foreach (var h in _catalog.Heroes.Where(x => x.Story)) { var panel = Panel(grid); var row = Row(panel); Image(row, h.Asset, 80, 110); var info = VBox(row); Text(info, h.Name + " · " + h.Rarity, 21, _gold); Text(info, $"第{h.Unlock}关 · {Catalog.Regions[h.Region]}", 12, _muted); if (!S.Story.Contains(h.Id)) Button(panel, "阅读剧情 · 结缘", () => StoryDialog(h), true, Rules.MaxClear(S) < h.Unlock); else { int trial = S.Trials.GetValueOrDefault(h.Id); Button(panel, $"个人历练 {trial}/5", () => TrialDialog(h), disabled: trial == 5); Button(panel, "查看名将", () => { _hero = h.Id; _page = "heroes"; Render(); }); } } }
    private void Settings() { Heading("SYSTEM / 设置", "把归途，妥善保存", "原生文件存档，自动保存与上一版备份。可导入浏览器v0.1.0导出文件。"); var panel = Panel(_body); Text(panel, "存档位置", 22, _gold); Text(panel, _savePath, 13, _muted); var row = Row(panel); Button(row, "导出存档", () => FileDialog(false), true); Button(row, "导入存档", () => FileDialog(true)); Button(row, "读取自动备份", () => Confirm("读取自动备份", "将回退到上一版保存状态。建议先导出当前存档。", () => { try { var loaded = SaveCodec.Decode(_catalog, System.IO.File.ReadAllText(_savePath + ".backup")); _engine.Import(loaded); CloseDialog(); Render(); Notice("已恢复备份。"); } catch (Exception e) { Notice(e.Message); } })); Button(row, "打开存档目录", () => OS.ShellOpen(System.IO.Path.GetDirectoryName(_savePath)!)); Button(panel, _sound ? "关闭占位音效" : "开启占位音效", () => { _sound = !_sound; Render(); }); Text(panel, "Godot 4.5 .NET / .NET 8 / C# 原生逻辑\n不使用WebView，不依赖JavaScript运行时。", 17, _jade); Text(panel, "人物、敌人、建筑、场景、装备、UI、特效和音频位于Assets。修改manifest.json即可替换素材。正式剧情、人物独有技能与商业平衡仍需继续制作。", 14, _muted); Button(panel, "打开工程资源目录", () => OS.ShellOpen(ProjectSettings.GlobalizePath("res://Assets"))); }
    private void ShowDialog(string title, Action<VBoxContainer> build, bool required = false, int width = 720, int height = 570) { CloseDialog(); _dialog = new Window { Title = title, Size = new Vector2I(width, height), Transient = true, Exclusive = true, Unresizable = false, Theme = _theme }; AddChild(_dialog); var m = new MarginContainer(); m.SetAnchorsAndOffsetsPreset(LayoutPreset.FullRect); foreach (var side in new[] { "left", "right", "top", "bottom" }) m.AddThemeConstantOverride("margin_" + side, 25); _dialog.AddChild(m); var scroll = new ScrollContainer { SizeFlagsHorizontal = SizeFlags.ExpandFill, SizeFlagsVertical = SizeFlags.ExpandFill, HorizontalScrollMode = ScrollContainer.ScrollMode.Disabled }; m.AddChild(scroll); var v = VBox(scroll, 15); Text(v, title, 26, _gold); build(v); _dialog.CloseRequested += () => { if (!required) CloseDialog(); }; _dialog.PopupCentered(); }
    private void CloseDialog() { if (_dialog != null) { _dialog.Hide(); _dialog.QueueFree(); _dialog = null; } _offerId = null; }
    private void OfferDialog() { var offer = S.Pending!; ShowDialog(offer.Kind == "loot" ? "首领首通 · 构筑宝箱" : "招贤席 · 请君择一", v => { Text(v, "本席已预付，关闭游戏也会保存原候选。选择一项，不额外扣费。", 14, _muted); var row = Row(v); for (int i = 0; i < offer.Options.Count; i++) { int index = i; var o = offer.Options[i]; var card = VBox(row); if (offer.Kind == "recruit") { HeroCard(card, _catalog.ById[o.Id], () => Try(new("choose", offer.Id, Index: index))); Text(card, o.Type == "hero" && !S.Heroes.ContainsKey(o.Id) ? "结识新人物" : $"培养碎片 ×{o.Amount}", 14, _jade); } else { Image(card, "icon." + o.Item!.Slot, 120, 120); Text(card, o.Item.Name, 21); Text(card, $"史诗 · 装等{o.Item.Level}\n主属性{o.Item.Power}", 14, _muted); } Button(card, "选择这一项", () => Try(new("choose", offer.Id, Index: index)), true, tag: "offer-choice-" + index); } if (offer.Results.Count > 0) Text(v, "已入账：" + string.Join("、", offer.Results.Select(x => _catalog.ById[x.Id].Name + (x.IsNew ? "（新）" : "×20片"))), 12, _muted); }, true, 800, 570); _offerId = offer.Id; }
    private void FormationDialog(int slot) { ShowDialog($"选择{(slot < 3 ? "前" : "后")}排名将", v => { Text(v, "同一人物不重复占格；已上阵人物与目标位置交换。", 14, _muted); var grid = new GridContainer { Columns = 4, SizeFlagsHorizontal = SizeFlags.ExpandFill }; v.AddChild(grid); foreach (var id in S.Heroes.Keys) HeroCard(grid, _catalog.ById[id], () => { CloseDialog(); Try(new("formation", id, slot)); }); Button(v, "清空该阵位", () => { CloseDialog(); Try(new("formation", Number: slot)); }); }, width: 820, height: 650); }
    private void StoryDialog(HeroDef h) { ShowDialog("结缘 · " + h.Name, v => { Image(v, h.Asset, 180, 210); Text(v, $"“山河虽异，心中之志未改。宗主，愿与你同行，寻回众人的归途。”\n\n你以洞天为誓，邀其同探归墟。{h.Name}轻轻颔首，一个新的名字在归途名册上亮起。", 18); Button(v, "邀请加入洞天", () => { CloseDialog(); Try(new("story", h.Id)); }, true); }); }
    private void TrialDialog(HeroDef h) { int i = S.Trials.GetValueOrDefault(h.Id); ShowDialog(h.Name + " · 个人历练", v => { Text(v, $"第{i + 1}项历练\n主线通关第{Math.Max(h.Unlock, Catalog.Gates[i])}关\n人物达到{Catalog.Caps[i]}级\n消耗{20 * (i + 1)}灵草\n获得{Catalog.Costs[i]}本人碎片", 20); Text(v, "每项只完成一次，无日期限制。当前为条件历练；独立人物战斗属于后续内容制作。", 13, _muted); Button(v, "完成历练", () => { CloseDialog(); Try(new("trial", h.Id)); }, true); }); }
    private void EndingDialog() => ShowDialog("终章 · 此间山河，来日再会", v => { Text(v, "九十六个名字化为星光，归墟不再吞噬往昔。你终于推开回到现实的门。\n\n“宗主，若有来日，愿再同行。”\n\n你睁开眼睛。屏幕上仍是熟悉的标题，掌心却留着一枚温热的玉印。旅途已经完成，洞天依然为你保留。", 20); Button(v, "留在洞天继续探索", CloseDialog, true); });
    private void Confirm(string title, string text, Action action) => ShowDialog(title, v => { Text(v, text, 18); Button(v, "确认", action, true); Button(v, "取消", CloseDialog); }, height: 310);
    private void FileDialog(bool import) { var d = new Godot.FileDialog { Title = import ? "导入存档" : "导出存档", Access = Godot.FileDialog.AccessEnum.Filesystem, FileMode = import ? Godot.FileDialog.FileModeEnum.OpenFile : Godot.FileDialog.FileModeEnum.SaveFile, Filters = ["*.json ; SHUABAO save"], CurrentFile = import ? "" : "SHUABAO-Godot.save.json", Size = new Vector2I(850, 600), Theme = _theme }; AddChild(d); d.FileSelected += path => { try { if (import) { var state = SaveCodec.Decode(_catalog, System.IO.File.ReadAllText(path)); Confirm("导入存档", $"将载入{state.Heroes.Count}位名将、已通关{Rules.MaxClear(state)}关的存档。当前进度保留为备份。", () => { try { _engine.Import(state); CloseDialog(); _stage = Math.Min(120, Rules.MaxClear(S) + 1); _region = (_stage - 1) / 30; Render(); Notice("存档已载入。"); } catch (Exception e) { Notice(e.Message); } }); } else { System.IO.File.WriteAllText(path, SaveCodec.Encode(S)); Notice("已导出存档：" + path); } } catch (Exception e) { Notice(e.Message); } d.QueueFree(); }; d.Canceled += () => d.QueueFree(); d.PopupCentered(); }
    private void Sound(string name) { if (!_sound) return; var player = new AudioStreamPlayer { Stream = _assets.Audio("audio." + name), VolumeDb = -15 }; AddChild(player); player.Finished += () => player.QueueFree(); player.Play(); }
    private void ShowFatal(Exception error) { GD.PushError(error.ToString()); if (_smoke) { GetTree().Quit(1); return; } foreach (var child in GetChildren()) child.QueueFree(); var v = VBox(this); Text(v, "暂时无法展开绘卷", 30, _gold); Text(v, error.Message + "\n现有存档没有清空。若已有另一实例在运行，请先关闭它。", 18); Button(v, "打开存档目录", () => OS.ShellOpen(System.IO.Path.GetDirectoryName(_savePath) ?? ProjectSettings.GlobalizePath("user://"))); Button(v, "退出", () => GetTree().Quit()); }
    private async void Smoke() { try { var pages = new[] { "battle", "heroes", "summon", "bag", "sect", "story", "settings" }; foreach (var page in pages) { _page = page; Render(); await ToSignal(GetTree(), SceneTree.SignalName.ProcessFrame); } Try(new("draw", Number: 0)); Rules.Require(S.Pending != null, "招募界面没有生成选择"); var before = SaveCodec.Encode(S); var restored = SaveCodec.Decode(_catalog, before); Rules.Require(restored.Pending!.Id == S.Pending!.Id, "未决选择恢复失败"); Try(new("choose", S.Pending.Id, Index: 0)); var ids = S.Heroes.Keys.Take(6).ToArray(); for (int i = 0; i < ids.Length; i++) Try(new("formation", ids[i], i), false); _page = "battle"; Try(new("battle", Number: 1)); for (int i = 0; i < 1000 && S.Encounter?.Status == "active"; i++) _engine.Execute(new("step"), Now); Rules.Require(S.Encounter?.Status == "victory", "首关未胜利"); var reward = (Reward)_engine.Execute(new("settle"), Now)!; Rules.Require(reward.Tickets == 10, "首关奖励非10券"); Try(new("dispatch", Number: 1)); foreach (var page in pages) { _page = page; Render(); await ToSignal(GetTree(), SceneTree.SignalName.ProcessFrame); } GD.Print("SHUABAO_GODOT_SMOKE_PASS: 7 pages, recruit, choice recovery, formation, three-wave win, dispatch"); GetTree().Quit(); } catch (Exception e) { GD.PushError(e.ToString()); GetTree().Quit(1); } }
}
