using Shuabao.Core;
using System.Text.Json;
using System.Text.Json.Nodes;
var catalog = Catalog.Load(File.ReadAllText(Path.Combine(AppContext.BaseDirectory, "catalog.json")));
const long now = 1000000000;
var passed = new List<string>(); var failures = new List<string>();
void Check(bool ok, string why = "assertion failed") { if (!ok) throw new Exception(why); }
void Equal<T>(T a, T b) => Check(JsonSerializer.Serialize(a, Json.Options) == JsonSerializer.Serialize(b, Json.Options), $"expected {JsonSerializer.Serialize(b, Json.Options)}; got {JsonSerializer.Serialize(a, Json.Options)}");
void Throws(Action action) { try { action(); } catch { return; } throw new Exception("Expected rejection"); }
void Test(string name, Action test) { try { test(); passed.Add(name); Console.WriteLine("PASS " + name); } catch (Exception e) { failures.Add(name + ": " + e.Message); Console.WriteLine("FAIL " + name + ": " + e); } }
GameEngine New(long seed = 3) => new(catalog, Model.New(catalog, seed, now));
object? Run(GameEngine e, Command cmd, long time = now) => e.Execute(cmd, time);
void Choose(GameEngine e) { if (e.State.Pending != null) Run(e, new("choose", e.State.Pending.Id, Index: 0)); }
void Pack(GameEngine e, int region = 0) { Run(e, new("draw", Number: region)); Choose(e); }
Reward Fight(GameEngine e, int stage) { Run(e, new("battle", Number: stage)); int n = 0; while (e.State.Encounter!.Status == "active" && n++ < 2500) Run(e, new("step")); var reward = (Reward)Run(e, new("settle"))!; Choose(e); return reward; }
void Fill(GameEngine e) => e.State.Heroes.Keys.Take(6).Select((id, i) => (id, i)).ToList().ForEach(x => Run(e, new("formation", x.id, x.i)));
string Fixture(string name) => File.ReadAllText(Path.Combine(AppContext.BaseDirectory, "Fixtures", name));
Test("catalog closes: 96 persons, 120 three-wave stages, 24 story heroes", () => { catalog.Validate(); Equal(catalog.Heroes.Count(h => h.Story), 24); });
Test("RNG matches browser golden vectors", () => { var g = JsonNode.Parse(Fixture("web-golden.json"))!; var r = new RandomStream(3, "recruit/0/0"); foreach (var value in g["random"]!.AsArray()) Equal(r.Next(), value!.GetValue<double>()); });
Test("C# draw results, options and stats match browser golden", () => { var e = New(); Run(e, new("draw", Number: 0)); var g = JsonNode.Parse(Fixture("web-golden.json"))!; foreach (var pair in g["heroes"]!.AsObject()) { Check(e.State.Heroes.ContainsKey(pair.Key)); Equal(e.State.Heroes[pair.Key].Level, pair.Value!["level"]!.GetValue<int>()); var expected = g["stats"]![pair.Key]!.Deserialize<Stats>(Json.Options); Equal(Model.Compute(catalog, e.State, pair.Key), expected!); } Equal(e.State.Pending!.Options.Select(x => x.Id).ToArray(), g["options"]!.AsArray().Select(x => x!["id"]!.GetValue<string>()).ToArray()); Equal(e.State.Fragments, g["fragments"]!.Deserialize<Dictionary<string, int>>(Json.Options)!); });
Test("normal pools never emit story cards or fragments", () => { var s = Model.New(catalog, 8, now); s.Resources["ticket"] = 3000; s.Cleared = [120]; for (int region = 0; region < 4; region++) for (int i = 0; i < 35; i++) { Recruitment.Draw(catalog, s, region, false); Check(s.Pending!.Options.All(o => !catalog.ById[o.Id].Story)); Recruitment.Choose(catalog, s, s.Pending.Id, 0); } Check(s.Heroes.Keys.All(id => !catalog.ById[id].Story) && s.Fragments.Keys.All(id => !catalog.ById[id].Story)); });
Test("all four pools close within 18 packs for 100 seeds", () => { for (int seed = 0; seed < 100; seed++) { var s = Model.New(catalog, seed, now); s.Resources["ticket"] = 720; s.Cleared = [120]; for (int region = 0; region < 4; region++) { for (int i = 0; i < 18; i++) { Recruitment.Draw(catalog, s, region, false); int option = s.Pending!.Options.FindIndex(x => !s.Heroes.ContainsKey(x.Id)); Recruitment.Choose(catalog, s, s.Pending.Id, Math.Max(0, option)); } Check(catalog.Heroes.Where(h => h.Region == region && !h.Story).All(h => s.Heroes.ContainsKey(h.Id))); } } });
Test("nine singles plus tenth equal a ten pack", () => { var a = New(); var b = New(); Run(a, new("draw", Number: 0)); for (int i = 0; i < 10; i++) Run(b, new("draw", Number: 0, Single: true)); Equal(a.State.Heroes, b.State.Heroes); Equal(a.State.Fragments, b.State.Fragments); Equal(a.State.Pending!.Options, b.State.Pending!.Options); Equal(a.State.Resources, b.State.Resources); });
Test("partial pack charges remaining count only", () => { var e = New(); Run(e, new("draw", Number: 0, Single: true)); Equal(e.State.Resources["ticket"], 29L); Run(e, new("draw", Number: 0)); Equal(e.State.Resources["ticket"], 20L); });
Test("paid offer persists and choice is idempotent", () => { var e = New(); Run(e, new("draw", Number: 0)); var restored = new GameEngine(catalog, SaveCodec.Decode(catalog, SaveCodec.Encode(e.State))); var id = restored.State.Pending!.Id; Run(restored, new("choose", id, Index: 0)); var resources = Json.Copy(restored.State.Resources); Run(restored, new("choose", id, Index: 0)); Equal(restored.State.Resources, resources); });
Test("pending offer blocks economic mutations", () => { var e = New(); Run(e, new("draw", Number: 0)); Throws(() => Run(e, new("draw", Number: 0))); Throws(() => Run(e, new("battle", Number: 1))); });
Test("failed commands are atomic", () => { var e = New(); Run(e, new("draw", Number: 0)); string before = SaveCodec.Encode(e.State); Throws(() => Run(e, new("choose", e.State.Pending!.Id, Index: 99))); Equal(SaveCodec.Encode(e.State), before); });
Test("failed disk writes do not advance authority", () => { var state = Model.New(catalog, 3, now); var e = new GameEngine(catalog, state, _ => throw new IOException("full")); Throws(() => Run(e, new("draw", Number: 0))); Equal(e.State, state); });
Test("reward receipt idempotency and repeat victory payout", () => { var s = Model.New(catalog, 3, now); Economy.Reward(s, 1, "a"); Economy.Reward(s, 10, "b"); Economy.Reward(s, 10, "b"); Economy.Reward(s, 10, "c"); Equal(s.Resources["ticket"], 100L); Equal(s.ClearCounts[10], 2); });
Test("120 wins award exactly 1440 tickets", () => { var s = Model.New(catalog, 3, now); for (int i = 1; i <= 120; i++) Economy.Reward(s, i, "win" + i); Equal(s.Resources["ticket"], 1470L); });
Test("battle restarts from saved action boundary deterministically", () => { var a = New(); Pack(a); Fill(a); Run(a, new("battle", Number: 1)); for (int i = 0; i < 5; i++) Run(a, new("step")); var b = new GameEngine(catalog, SaveCodec.Decode(catalog, SaveCodec.Encode(a.State))); while (a.State.Encounter!.Status == "active") { Run(a, new("step")); Run(b, new("step")); Equal(a.State.Encounter, b.State.Encounter); } });
Test("web in-progress battle migrates and finishes with identical final HP", () => { var e = new GameEngine(catalog, SaveCodec.Decode(catalog, Fixture("web-battle.json"))); while (e.State.Encounter!.Status == "active") Run(e, new("step")); var expected = JsonNode.Parse(Fixture("web-golden.json"))!["battle"]!.Deserialize<BattleState>(Json.Options)!; Equal(e.State.Encounter.Status, expected.Status); Equal(e.State.Encounter.Step, expected.Step); Equal(e.State.Encounter.Units.Select(x => x.Hp).ToArray(), expected.Units.Select(x => x.Hp).ToArray()); });
Test("web paid recruit offer migrates without reroll or extra fee", () => { var state = SaveCodec.Decode(catalog, Fixture("web-pending.json")); Equal(state.Schema, 2); Equal(state.Rules, Catalog.Version); var e = new GameEngine(catalog, state); var ticket = state.Resources["ticket"]; Choose(e); Equal(e.State.Resources["ticket"], ticket); });
Test("wave transitions preserve survivors HP and defeated status", () => { var e = New(); Run(e, new("battle", Number: 1)); var b = e.State.Encounter!; var allies = b.Units.Where(u => u.Side == "ally").ToList(); allies[0].Hp = 0; allies[1].Hp = 123; foreach (var enemy in b.Units.Where(u => u.Side == "enemy")) enemy.Hp = 0; b.Queue = [allies[0].Id]; Run(e, new("step")); Equal(e.State.Encounter!.Wave, 2); Equal(e.State.Encounter.Units.Find(u => u.Id == allies[0].Id)!.Hp, 0); Equal(e.State.Encounter.Units.Find(u => u.Id == allies[1].Id)!.Hp, 123); });
Test("boss choice grants exactly one item and is first-clear only", () => { var e = New(); e.State.Cleared = [9]; e.State.Encounter = new() { Id = "fake_win", Stage = 10, Status = "victory", Team = [], Units = [] }; Run(e, new("settle")); Check(e.State.Pending!.Kind == "loot"); int count = e.State.Items.Count; string offer = e.State.Pending.Id; Run(e, new("choose", offer, Index: 0)); Run(e, new("choose", offer, Index: 0)); Equal(e.State.Items.Count, count + 1); e.State.Encounter = new() { Id = "fake_win2", Stage = 10, Status = "victory", Team = [], Units = [] }; Run(e, new("settle")); Check(e.State.Pending == null); });
Test("promotion requires cap, milestone and finite shards", () => { var e = New(); string id = e.State.Heroes.Keys.First(); e.State.Heroes[id].Level = 20; e.State.Fragments[id] = 20; Throws(() => Run(e, new("promote", id))); e.State.Cleared = [10]; Run(e, new("promote", id)); Equal(e.State.Heroes[id].Rank, 1); Equal(e.State.Fragments[id], 0); });
Test("story heroes cannot consume universal shards", () => { var e = New(); e.State.Cleared = [120]; string id = catalog.Heroes.First(h => h.Story).Id; Run(e, new("story", id)); e.State.Heroes[id].Level = 20; e.State.Resources["echo"] = 1000; Throws(() => Run(e, new("promote", id))); });
Test("story grant and personal trial are unique", () => { var e = New(); var h = catalog.Heroes.First(h => h.Story); Throws(() => Run(e, new("story", h.Id))); e.State.Cleared = [10]; Run(e, new("story", h.Id)); Run(e, new("story", h.Id)); Equal(e.State.Fragments[h.Id], 0); e.State.Heroes[h.Id].Level = 20; Run(e, new("trial", h.Id)); Equal(e.State.Fragments[h.Id], 20); Throws(() => Run(e, new("trial", h.Id))); });
Test("equipment has one owner, lock and equipped protection", () => { var e = New(); var ids = e.State.Heroes.Keys.ToArray(); var item = Economy.MakeItem(e.State, 5, "test", "weapon"); Economy.StoreItem(e.State, item); Run(e, new("equip", ids[0], Other: item.Id)); Run(e, new("equip", ids[1], Other: item.Id)); Check(!e.State.Heroes[ids[0]].Equipment.ContainsKey("weapon")); Throws(() => Run(e, new("dismantle", item.Id))); int before = Model.Compute(catalog, e.State, ids[1]).Atk; Run(e, new("enhance", item.Id)); Check(Model.Compute(catalog, e.State, ids[1]).Atk > before); });
Test("offline catch-up equals incremental online accounting", () => { var a = Model.New(catalog, 3, now); a.Cleared = [1]; Economy.StartDispatch(a, 1); var b = Json.Copy(a); for (int i = 1; i <= 60; i++) Economy.Advance(catalog, a, now + i * 60000); Economy.Advance(catalog, b, now + 3600000); Equal(a, b); Equal(a.Resources["ticket"], 90L); });
Test("48h cap, rollback clock and duplicate accounting", () => { var s = Model.New(catalog, 3, now); s.Cleared = [10]; Economy.StartDispatch(s, 10); var r = Economy.Advance(catalog, s, now + 72 * 3600000); Equal(r.Cycles, 96); Equal(s.Resources["ticket"], 2910L); var before = Json.Copy(s); Economy.Advance(catalog, s, now + 70 * 3600000); Equal(s, before); Economy.Advance(catalog, s, now + 72 * 3600000); Equal(s, before); Check(s.ClearCounts.Count == 0); });
Test("battle pauses dispatch and retains partial progress", () => { var e = New(); e.State.Cleared = [1]; Run(e, new("dispatch", Number: 1)); Run(e, new("clock"), now + 300000); Run(e, new("battle", Number: 1), now + 300000); Check(e.State.Dispatch!.Paused); Run(e, new("retreat"), now + 900000); Run(e, new("dispatch-resume"), now + 900000); Run(e, new("clock"), now + 1200000); Equal(e.State.Dispatch.Index, 1L); });
Test("native atomic file backup and corruption recovery", () => { string dir = Path.Combine(Path.GetTempPath(), "shuabao-test-" + Guid.NewGuid()); Directory.CreateDirectory(dir); try { string path = Path.Combine(dir, "save.json"); var a = Model.New(catalog, 3, now); SaveCodec.WriteAtomic(path, a); var b = Json.Copy(a); b.Resources["gold"]++; SaveCodec.WriteAtomic(path, b); File.WriteAllText(path, "corrupt"); var loaded = SaveCodec.Read(catalog, path); Check(loaded.Recovered); Equal(loaded.State!, a); } finally { Directory.Delete(dir, true); } });
Test("invalid imported state is rejected before replacing authority", () => { var e = New(); var bad = Json.Copy(e.State); bad.Formation = ["not-a-hero", null, null, null, null, null]; string before = SaveCodec.Encode(e.State); Throws(() => e.Import(bad)); Equal(SaveCodec.Encode(e.State), before); });
Test("last normal recruit after final boss triggers ending", () => { var e = New(); var missing = catalog.Heroes.First(h => h.Region == 3 && !h.Story); foreach (var h in catalog.Heroes.Where(h => h.Id != missing.Id)) Model.GrantHero(catalog, e.State, h.Id); e.State.Cleared = [120]; e.State.Draws[3] = 9; Run(e, new("draw", Number: 3, Single: true)); int index = e.State.Pending!.Options.FindIndex(x => x.Id == missing.Id); Run(e, new("choose", e.State.Pending.Id, Index: index)); Check(e.State.Ending); });

if (args.Contains("--playthrough")) Test("120-stage real economy playthrough reaches 96/96 ending", () =>
{
    var e = New(); var rows = new List<object>(); bool TryRun(Command cmd) { try { Run(e, cmd); return true; } catch { return false; } }
    void Prepare(int stage) { int region = (stage - 1) / 30; while (e.State.Resources["ticket"] >= 10) Pack(e, region); foreach (var h in catalog.Heroes.Where(h => h.Story && h.Unlock < stage)) TryRun(new("story", h.Id)); var team = new[] { "曹仁", "廖化", "黄忠", "华佗", "荀攸", "周瑜" }.Select(n => catalog.Heroes.Single(h => h.Name == n).Id).Where(e.State.Heroes.ContainsKey).ToList(); foreach (var id in e.State.Heroes.Keys) if (team.Count < 6 && !team.Contains(id)) team.Add(id); for (int i = 0; i < team.Count; i++) Run(e, new("formation", team[i], i)); for (int round = 0; round < 10; round++) foreach (var id in team) { TryRun(new("train", id, 1)); TryRun(new("promote", id)); } foreach (var id in team) foreach (var slot in Catalog.Slots) { var used = e.State.Heroes.Values.Where(h => h.Id != id).SelectMany(h => h.Equipment.Values).ToHashSet(); var best = e.State.Items.Where(it => it.Slot == slot && !used.Contains(it.Id)).OrderByDescending(it => it.Power).FirstOrDefault(); if (best != null) TryRun(new("equip", id, Other: best.Id)); } }
    for (int stage = 1; stage <= 120; stage++) { Prepare(stage); var reward = Fight(e, stage); int retry = 0; while (reward.Defeat && stage > 1 && retry++ < 3) { Fight(e, stage - 1); Prepare(stage); reward = Fight(e, stage); } Check(!reward.Defeat, $"Could not clear {stage}"); rows.Add(new { stage, retry, levels = e.State.Formation.Where(x => x != null).Select(x => e.State.Heroes[x!].Level).ToArray() }); }
    foreach (var h in catalog.Heroes.Where(h => h.Story)) TryRun(new("story", h.Id)); Check(e.State.Ending && e.State.Heroes.Count == 96); var report = new { seed = 3, stages = 120, collected = e.State.Heroes.Count, ending = e.State.Ending, finalResources = e.State.Resources, rows }; Directory.CreateDirectory("Docs/QA"); File.WriteAllText("Docs/QA/playthrough.json", JsonSerializer.Serialize(report, new JsonSerializerOptions(Json.Options) { WriteIndented = true }));
});
Directory.CreateDirectory("Docs/QA"); File.WriteAllText("Docs/QA/core-tests.json", JsonSerializer.Serialize(new { passed = passed.Count, failed = failures.Count, tests = passed, failures }, new JsonSerializerOptions { WriteIndented = true })); Console.WriteLine($"RESULT {passed.Count} passed, {failures.Count} failed"); return failures.Count == 0 ? 0 : 1;
