namespace Shuabao.Core;
public static class Battle
{
    private static List<Unit> Alive(IEnumerable<Unit> units) => units.Where(u => u.Hp > 0).ToList();
    public static string Start(Catalog c, GameState s, int stage)
    {
        Rules.Require(stage >= 1 && stage <= Math.Min(120, Rules.MaxClear(s) + 1), "关卡尚未开放"); Rules.Require(s.Encounter == null, "已有战斗"); var team = s.Formation.Where(x => x != null).Select(x => x!).ToList(); Rules.Require(team.Count > 0, "至少上阵一人"); foreach (var key in s.Workers.Where(x => team.Contains(x.Value)).Select(x => x.Key).ToArray()) s.Workers.Remove(key); if (s.Dispatch != null) s.Dispatch.Paused = true; var b = new BattleState { Id = Rules.Id(s, "encounter"), Stage = stage, Team = team, Roles = Catalog.Roles.Keys.ToDictionary(k => k, k => team.Count(id => c.ById[id].Role == k)) };
        for (int slot = 0; slot < 6; slot++) { var id = s.Formation[slot]; if (id == null) continue; var def = c.ById[id]; var st = Model.Compute(c, s, id); if (b.Roles["guard"] >= 2) st.Hp = Rules.Round(st.Hp * 1.1); if (b.Roles["striker"] >= 2) st.Atk = Rules.Round(st.Atk * 1.1); if (b.Roles["mage"] >= 2) st.Magic = Rules.Round(st.Magic * 1.1); if (b.Roles["archer"] >= 2) st.Speed += 10; b.Units.Add(new() { Id = id, Source = id, Name = def.Name, Role = def.Role, Side = "ally", Slot = slot, Stats = st, Hp = st.Hp, Mp = st.Mp, Sp = st.Stamina, Skills = [.. s.Heroes[id].Skills], Rank = s.Heroes[id].Rank }); }
        s.Encounter = b; Spawn(c, b); return b.Id;
    }
    private static void Spawn(Catalog c, BattleState b) { b.Units = b.Units.Where(u => u.Side == "ally").ToList(); var stage = c.Stages[b.Stage - 1]; int n = stage.Boss && b.Wave == 3 ? 3 : Math.Min(6, 2 + b.Stage / 8); double scale = 1 + b.Stage * .052 + (b.Stage - 1) / 30 * .5; for (int i = 0; i < n; i++) { bool boss = stage.Boss && b.Wave == 3 && i == 0; string role = boss ? "mage" : new[] { "striker", "guard", "archer", "controller", "healer", "mage" }[(i + b.Wave - 1) % 6]; int hp = Rules.Round((boss ? 1700 : 220 + 30 * b.Wave) * scale); var st = new Stats { Hp = hp, Atk = Rules.Round((boss ? 100 : 49) * scale), Magic = Rules.Round((boss ? 100 : 50) * scale), Def = Rules.Round(15 * scale), Mdef = Rules.Round(12 * scale), Speed = 45 + i * 5, Mp = 90, Stamina = 100, Crit = 5 }; b.Units.Add(new() { Id = $"enemy_{b.Wave}_{i}", Name = boss ? stage.Name : new[] { "玄甲兵", "山野游骑", "阵法术士", "幽火侍卫", "迷途剑客", "药师傀儡" }[i % 6], Role = role, Side = "enemy", Slot = i, Stats = st, Hp = hp, Mp = 90, Sp = 100, Boss = boss }); } b.Round = 0; b.Queue.Clear(); Log(b, $"第 {b.Wave} 波敌人抵达。"); }
    private static void Log(BattleState b, string text) { b.Log.Add(text); if (b.Log.Count > 90) b.Log.RemoveAt(0); }
    private static int Damage(BattleState b, Unit actor, Unit target, double amount, RandomStream r, bool magic = false) { if (target.Side == actor.Side || target.Hp <= 0) return 0; bool crit = r.Next() * 100 < actor.Stats.Crit; int n = Math.Max(1, Rules.Round((amount - (magic ? target.Stats.Mdef : target.Stats.Def) * .7) * (crit ? 1.5 : 1) * (target.Mark > 0 ? 1.2 : 1))); int absorbed = Math.Min(n, target.Shield); target.Shield -= absorbed; n -= absorbed; target.Hp = Math.Max(0, target.Hp - n); b.LastEvent = new() { Actor = actor.Id, Target = target.Id, Amount = n, Crit = crit }; Log(b, $"{actor.Name} → {target.Name} {(crit ? "会心 " : "")}{n}{(absorbed > 0 ? $"（护盾{absorbed}）" : "")}{(target.Hp == 0 ? " · 倒下" : "")}"); if (target.Hp > 0 && target.Skills.Contains("riposte") && !target.Reacted) { target.Reacted = true; int back = Math.Max(1, Rules.Round(target.Stats.Atk * .35)); actor.Hp = Math.Max(0, actor.Hp - back); Log(b, $"{target.Name}反击 {back}"); } return n; }
    private static Unit Target(Unit a, List<Unit> enemies) { var taunt = enemies.Find(x => x.Taunt > 0); if (taunt != null) return taunt; var back = enemies.Where(x => x.Slot >= 3).ToList(); var front = enemies.Where(x => x.Slot < 3).ToList(); var list = a.Role == "archer" && back.Count > 0 ? back : front.Count > 0 ? front : enemies; return list.OrderByDescending(x => x.Mark).ThenBy(x => Math.Abs(x.Slot % 3 - a.Slot % 3)).ThenBy(x => x.Hp).First(); }
    public static string Step(Catalog c, GameState s, string? action = null, string? targetId = null)
    {
        var b = s.Encounter; Rules.Require(b?.Status == "active", "没有正在进行的战斗"); if (b!.Queue.Count == 0) { b.Round++; foreach (var u in b.Units) u.Reacted = false; b.Queue = Alive(b.Units).OrderByDescending(u => u.Stats.Speed).ThenBy(u => u.Id, StringComparer.Ordinal).Select(u => u.Id).ToList(); }
        var id = b.Queue[0]; b.Queue.RemoveAt(0); var a = b.Units.Find(u => u.Id == id); if (a == null || a.Hp <= 0) return Finish(c, b); b.Step++; var r = new RandomStream(s.Seed, $"combat/{b.Id}/{b.Step}"); a.Cd = Math.Max(0, a.Cd - 1); a.Sp = Math.Min(a.Stats.Stamina, a.Sp + (int)Math.Ceiling(a.Stats.Stamina * .1)); a.Taunt = Math.Max(0, a.Taunt - 1); a.Mark = Math.Max(0, a.Mark - 1);
        if (a.Burn > 0) { int n = Rules.Round(a.Stats.Hp * .035); a.Hp = Math.Max(0, a.Hp - n); a.Burn--; Log(b, $"{a.Name}灼烧损失 {n}"); if (a.Hp == 0) return Finish(c, b); }
        if (a.Stun > 0) { a.Stun--; Log(b, $"{a.Name}受到控制，跳过行动"); return Finish(c, b); }
        var foes = Alive(b.Units.Where(u => u.Side != a.Side)); var friends = Alive(b.Units.Where(u => u.Side == a.Side)); if (foes.Count == 0) return Finish(c, b); var skill = Catalog.Skills[a.Role]; var lowest = friends.OrderBy(u => u.Hp / (double)u.Stats.Hp).First(); var target = Target(a, foes); bool manual = action != null && a.Side == "ally"; if (manual && targetId != null) { var requested = foes.Find(u => u.Id == targetId); if (requested != null && (a.Role is "archer" or "mage" or "controller" || requested.Slot < 3 || !foes.Any(u => u.Slot < 3))) target = requested; }
        if (a.Boss) { if (a.Charge) { foreach (var t in foes) Damage(b, a, t, a.Stats.Magic * 1.05, r, true); a.Charge = false; Log(b, $"{a.Name}释放天灾！"); return Finish(c, b); } if (b.Round % 3 == 0) { a.Charge = true; Log(b, $"{a.Name}正在蓄力！可控制打断，或守御治疗承受。"); return Finish(c, b); } }
        bool use = a.Cd == 0 && a.Mp >= skill.Cost && (a.Role != "healer" || lowest.Hp < lowest.Stats.Hp * .8); if (manual && action == "attack") use = false; if (manual && action == "rest" || a.Mp < skill.Cost || a.Sp < 8) { a.Mp = Math.Min(a.Stats.Mp, a.Mp + (int)Math.Ceiling(a.Stats.Mp * .25)); a.Sp = Math.Min(a.Stats.Stamina, a.Sp + 25); Log(b, $"{a.Name}调息，恢复灵力与体力"); return Finish(c, b); }
        if (use) { a.Mp -= skill.Cost; a.Sp -= 8; a.Cd = skill.Cd; a.Mastery = Math.Min(3, a.Mastery + 1); if (a.Skills.Contains("cleanse")) a.Burn = 0; double mult = (1 + a.Rank * .04) * (a.Skills.Contains("charge") ? 1.1 : 1); Log(b, $"{a.Name} · {skill.Name}"); switch (a.Role) { case "guard": a.Shield += Rules.Round(a.Stats.Hp * .22); a.Taunt = 2; Damage(b, a, target, a.Stats.Atk * .8 * mult, r); break; case "striker": target.Shield = 0; Damage(b, a, target, a.Stats.Atk * 1.65 * mult, r); break; case "archer": Damage(b, a, target, a.Stats.Atk * 1.35 * mult, r); target.Mark = 3; break; case "mage": foreach (var t in foes) { Damage(b, a, t, a.Stats.Magic * .68 * mult, r, true); t.Burn = 2; } break; case "healer": int n = Math.Min(lowest.Stats.Hp - lowest.Hp, Rules.Round(a.Stats.Magic * 1.8 * mult)); lowest.Hp += n; lowest.Burn = 0; b.LastEvent = new() { Actor = a.Id, Target = lowest.Id, Amount = n, Kind = "heal" }; Log(b, $"{a.Name}治疗{lowest.Name} {n}"); break; case "controller": target = foes.Find(u => u.Charge) ?? target; Damage(b, a, target, a.Stats.Magic * .95 * mult, r, true); target.Stun = 1; target.Charge = false; break; } }
        else { a.Sp -= 5; Damage(b, a, target, a.Stats.Atk, r); }
        return Finish(c, b);
    }
    private static string Finish(Catalog c, BattleState b) { if (!b.Units.Any(u => u.Side == "ally" && u.Hp > 0)) return b.Status = "defeat"; if (!b.Units.Any(u => u.Side == "enemy" && u.Hp > 0)) { if (b.Wave == 3) return b.Status = "victory"; b.Wave++; Spawn(c, b); return "wave"; } if (b.Round >= 150 && b.Queue.Count == 0) { Log(b, "久战未决，撤回洞天。"); return b.Status = "defeat"; } return "active"; }
}
