using System.Text.Json;
namespace Shuabao.Core;
public static class Economy
{
    public static Item MakeItem(GameState s, int stage, string address, string? slot = null) { var r = new RandomStream(s.Seed, $"loot/{address}"); int quality = r.Next() < .12 ? 3 : r.Next() < .4 ? 2 : 1; var chosen = slot ?? r.Pick(Catalog.Slots); var set = r.Pick(Catalog.Sets); return new() { Id = Rules.Id(s, "item"), Slot = chosen, Set = set, Quality = quality, Level = stage, Power = Rules.Round((8 + stage * 1.2) * (1 + quality * .2)), Affix = new() { Key = r.Pick(new[] { "atk", "magic", "def", "speed" }), Value = Math.Max(1, Rules.Round(2 + stage * .15)) }, Name = ItemName(set, chosen) }; }
    private static string ItemName(string set, string slot) => set + (slot switch { "weapon" => "长锋", "armor" => "战袍", "feet" => "行靴", _ => "玉佩" });
    public static void StoreItem(GameState s, Item item) => (s.Items.Count < 500 ? s.Items : s.Inbox).Add(item);
    public static Reward Reward(GameState s, int stage, string id, bool firstAllowed = true) { if (s.Receipts.TryGetValue(id, out var old)) return old.Deserialize<Reward>(Json.Options)!; bool boss = stage % 10 == 0; var b = new Reward { Stage = stage, Tickets = boss ? 30 : 10, Gold = 100 + stage * 15, Ore = 8 + (int)Math.Ceiling(stage / 3d), Xp = 100 + stage * 20 }; s.Resources["ticket"] += b.Tickets; s.Resources["gold"] += b.Gold; s.Resources["ore"] += b.Ore; s.Resources["xp"] += b.Xp; for (int i = 0; i < (boss ? 3 : 1); i++) { var item = MakeItem(s, stage, $"{id}/{i}"); StoreItem(s, item); b.Items.Add(item.Id); } if (firstAllowed) { s.ClearCounts[stage] = s.ClearCounts.GetValueOrDefault(stage) + 1; if (!s.Cleared.Contains(stage)) { s.Cleared.Add(stage); b.First = true; if (boss) { s.Resources["ore"] += 50; s.Resources["gold"] += 500; b.BossBonus = true; } } } s.Receipts[id] = JsonSerializer.SerializeToElement(b, Json.Options); return b; }
    public static Reward Settle(Catalog c, GameState s) { var b = s.Encounter; Rules.Require(b != null && b.Status != "active", "战斗尚未结束"); var result = new Reward { Stage = b!.Stage, Defeat = b.Status == "defeat" }; if (b.Status == "victory") { result = Reward(s, b.Stage, b.Id); if (result.BossBonus) s.Pending = new() { Id = Rules.Id(s, "boss_offer"), Kind = "loot", Stage = b.Stage, Options = Enumerable.Range(0, 3).Select(i => { var item = MakeItem(s, b.Stage, $"{b.Id}/firstchoice/{i}", Catalog.Slots[i]); item.Quality = 3; return new OfferOption { Id = item.Id, Type = "item", Item = item }; }).ToList() }; foreach (var id in b.Team) { var h = s.Heroes[id]; Model.Experience(h, 35 + b.Stage * 8); h.Mastery = Math.Min(100, h.Mastery + (b.Units.Find(u => u.Source == id)?.Mastery ?? 0)); } } s.Encounter = null; foreach (var building in c.Buildings.Where(x => Rules.MaxClear(s) >= x.Unlock)) s.Buildings.TryAdd(building.Id, 1); return result; }
    public static int Train(GameState s, string id, int count) { Rules.Require(s.Heroes.ContainsKey(id), "人物未招募"); var h = s.Heroes[id]; Rules.Require(!Model.Busy(s, id), "请先结束出征"); Rules.Require(h.Level < Catalog.Caps[h.Rank], "已达本阶上限，请突破"); int used = 0; for (int i = 0; i < count && h.Level < Catalog.Caps[h.Rank]; i++) { int cost = Math.Max(1, Model.LevelCost(h) - h.Xp); if (s.Resources["xp"] < cost) break; s.Resources["xp"] -= cost; Model.Experience(h, cost); used += cost; } Rules.Require(used > 0, "修为丹不足"); return used; }
    public static int Promote(Catalog c, GameState s, string id) { var h = s.Heroes[id]; Rules.Require(h.Rank < 5, "已完成六阶"); Rules.Require(!Model.Busy(s, id), "请先结束出征"); Rules.Require(h.Level == Catalog.Caps[h.Rank], $"需达到{Catalog.Caps[h.Rank]}级"); Rules.Require(Rules.MaxClear(s) >= Catalog.Gates[h.Rank], $"需通关第{Catalog.Gates[h.Rank]}关"); int cost = Catalog.Costs[h.Rank], own = Math.Min(cost, s.Fragments.GetValueOrDefault(id)), extra = cost - own; Rules.Require(!c.ById[id].Story || extra == 0, "剧情角色只接受专属历练碎片"); Rules.Require(s.Resources["echo"] >= extra, "人物碎片与残忆不足"); s.Fragments[id] -= own; s.Resources["echo"] -= extra; h.Rank++; if (h.Rank == 5 && !c.ById[id].Story) { s.Resources["echo"] += s.Fragments[id]; s.Fragments[id] = 0; } return h.Rank; }
    public static bool Story(Catalog c, GameState s, string id) { var d = c.ById[id]; Rules.Require(d.Story && Rules.MaxClear(s) >= d.Unlock, "尚未到达剧情节点"); if (s.Story.Contains(id)) return false; if (!s.Heroes.ContainsKey(id)) Model.GrantHero(c, s, id); s.Story.Add(id); return true; }
    public static int Trial(Catalog c, GameState s, string id) { int i = s.Trials.GetValueOrDefault(id); Rules.Require(s.Heroes.ContainsKey(id) && c.ById[id].Story && i < 5, "没有可完成的历练"); var h = s.Heroes[id]; Rules.Require(Rules.MaxClear(s) >= Math.Max(c.ById[id].Unlock, Catalog.Gates[i]), $"需通关第{Math.Max(c.ById[id].Unlock, Catalog.Gates[i])}关"); Rules.Require(h.Level >= Catalog.Caps[i] && h.Rank >= i, $"需达到{Catalog.Caps[i]}级"); int herb = 20 * (i + 1); Rules.Require(s.Resources["herb"] >= herb, $"需要{herb}灵草"); s.Resources["herb"] -= herb; Model.Fragments(c, s, id, Catalog.Costs[i]); s.Trials[id] = i + 1; return Catalog.Costs[i]; }
    public static void Equip(GameState s, string hero, string itemId) { Rules.Require(s.Heroes.ContainsKey(hero) && !Model.Busy(s, hero), "角色未招募或正在出征"); var item = s.Items.Find(x => x.Id == itemId); Rules.Require(item != null, "装备不在背包"); foreach (var h in s.Heroes.Values.Where(h => h.Equipment.ContainsValue(itemId))) { Rules.Require(!Model.Busy(s, h.Id), "原持有者正在出征"); h.Equipment.Remove(item!.Slot); } s.Heroes[hero].Equipment[item!.Slot] = item.Id; }
    public static void Enhance(GameState s, string id) { var item = s.Items.Find(x => x.Id == id); Rules.Require(item != null && item.Enhance < 10, "装备不存在或已满强化"); var owner = s.Heroes.Values.FirstOrDefault(h => h.Equipment.ContainsValue(id)); Rules.Require(owner == null || !Model.Busy(s, owner.Id), "出征装备不能强化"); int ore = 8 * (item!.Enhance + 1), gold = 100 * (item.Enhance + 1); Rules.Require(s.Resources["ore"] >= ore && s.Resources["gold"] >= gold, $"需要{ore}矿石、{gold}铜钱"); s.Resources["ore"] -= ore; s.Resources["gold"] -= gold; item.Enhance++; }
    public static void Dismantle(GameState s, string id) { var item = s.Items.Find(x => x.Id == id); Rules.Require(item != null && !item.Locked, "装备不存在或已锁定"); Rules.Require(!s.Heroes.Values.Any(h => h.Equipment.ContainsValue(id)), "先卸下装备"); s.Items.Remove(item!); s.Resources["ore"] += 5 + item!.Quality * 3 + item.Enhance * 4; }
    public static Item Craft(GameState s, string slot, string set) { Rules.Require(s.Buildings.ContainsKey("forge") && Catalog.Slots.Contains(slot) && Catalog.Sets.Contains(set), "锻造尚未开放"); Rules.Require(s.Resources["ore"] >= 50 && s.Resources["gold"] >= 350, "需要50矿石、350铜钱"); s.Resources["ore"] -= 50; s.Resources["gold"] -= 350; var item = MakeItem(s, Math.Max(5, Rules.MaxClear(s)), Rules.Id(s, "craft"), slot); item.Set = set; item.Name = ItemName(set, slot); item.Quality = Math.Max(2, item.Quality); StoreItem(s, item); return item; }
    public static void Upgrade(GameState s, string id) { Rules.Require(s.Buildings.TryGetValue(id, out int lv) && lv < 3, "建筑未开放或已满级"); Rules.Require(s.Resources["gold"] >= 800 * lv && s.Resources["ore"] >= 60 * lv, $"需要{800 * lv}铜钱、{60 * lv}矿石"); s.Resources["gold"] -= 800 * lv; s.Resources["ore"] -= 60 * lv; s.Buildings[id]++; }
    public static void Worker(GameState s, string building, string? id) { Rules.Require(s.Buildings.ContainsKey(building), "建筑未开放"); if (string.IsNullOrEmpty(id)) { s.Workers.Remove(building); return; } Rules.Require(s.Heroes.ContainsKey(id) && !Model.Busy(s, id), "角色未招募或正在出征"); foreach (var key in s.Workers.Where(x => x.Value == id).Select(x => x.Key).ToArray()) s.Workers.Remove(key); s.Workers[building] = id; }
    public static void Learn(GameState s, string id, string skill) { Rules.Require(s.Buildings.ContainsKey("library"), "第20关开放藏经阁"); Rules.Require(s.Heroes.ContainsKey(id) && Catalog.PublicSkills.ContainsKey(skill) && !Model.Busy(s, id), "战技无效或角色出征中"); var h = s.Heroes[id]; if (h.Skills.Remove(skill)) return; Rules.Require(h.Skills.Count < 3, "最多三个公共位"); var type = Catalog.PublicSkills[skill].Type; Rules.Require(type == "active" || !h.Skills.Any(x => Catalog.PublicSkills[x].Type == type), "该类战技最多一项"); Rules.Require(s.Resources["gold"] >= 200, "需要200铜钱"); s.Resources["gold"] -= 200; h.Skills.Add(skill); }
    public static void StartDispatch(GameState s, int stage) { Rules.Require(s.Encounter == null && s.Dispatch == null, "请先结束当前出征"); Rules.Require(s.Cleared.Contains(stage), "仅能委托已通关关卡"); var team = s.Formation.Where(x => x != null).Select(x => x!).ToList(); Rules.Require(team.Count > 0, "先配置队伍"); foreach (var k in s.Workers.Where(x => team.Contains(x.Value)).Select(x => x.Key).ToArray()) s.Workers.Remove(k); s.Dispatch = new() { Id = Rules.Id(s, "dispatch"), Stage = stage, Team = team, CycleMs = stage % 10 == 0 ? 1800000 : 600000 }; }
    public static ClockResult Advance(Catalog c, GameState s, long now)
    {
        Rules.Require(now >= 0, "时钟非法"); long raw = Math.Max(0, now - s.LastClock), elapsed = Math.Min(raw, 172800000); s.LastClock = Math.Max(now, s.LastClock); var result = new ClockResult { Elapsed = elapsed, Discarded = raw - elapsed }; if (s.Dispatch is { Paused: false } d) { d.Elapsed += elapsed; while (d.Elapsed >= d.CycleMs) { d.Elapsed -= d.CycleMs; Reward(s, d.Stage, $"{d.Id}/{d.Index++}", false); result.Cycles++; } }
        foreach (var def in c.Buildings) { if (!s.Buildings.TryGetValue(def.Id, out var lv) || def.Id == "summon") continue; if (!s.Jobs.TryGetValue(def.Id, out var j)) s.Jobs[def.Id] = j = new(); j.Elapsed += elapsed * (s.Workers.ContainsKey(def.Id) ? 2 : 1); long completed = j.Elapsed / 120000; j.Elapsed %= 120000; j.Index += completed; long amount = completed * lv * (def.Resource == "gold" ? 45 : def.Resource == "xp" ? 35 : 4); s.Resources[def.Resource] += amount; result.Outputs[def.Resource] = result.Outputs.GetValueOrDefault(def.Resource) + amount; }
        return result;
    }
}
