namespace Shuabao.Core;
public static class Model
{
    public static GameState New(Catalog c, long seed, long now) { var s = new GameState { Seed = seed, Created = now, LastClock = now, Mainline = c.Heroes.Select(h => h.Id).ToList() }; foreach (var name in new[] { "廖化", "糜竺", "荀攸" }) GrantHero(c, s, c.Heroes.Single(h => h.Name == name).Id); s.Formation = [c.Heroes.Single(h => h.Name == "廖化").Id, null, null, c.Heroes.Single(h => h.Name == "糜竺").Id, c.Heroes.Single(h => h.Name == "荀攸").Id, null]; return s; }
    public static bool GrantHero(Catalog c, GameState s, string id) { Rules.Require(c.ById.ContainsKey(id), "未知人物"); if (s.Heroes.ContainsKey(id)) { Fragments(c, s, id, 20); return false; } var levels = s.Formation.Where(x => x != null).Select(x => s.Heroes[x!].Level).Order().ToList(); int level = Math.Clamp((levels.Count == 0 ? 1 : levels[levels.Count / 2]) - 5, 1, 20); s.Heroes[id] = new() { Id = id, Level = level }; s.Fragments.TryAdd(id, 0); return true; }
    public static void Fragments(Catalog c, GameState s, string id, int n) { if (s.Heroes.TryGetValue(id, out var h) && h.Rank == 5 && !c.ById[id].Story) s.Resources["echo"] += n; else s.Fragments[id] = s.Fragments.GetValueOrDefault(id) + n; }
    public static int LevelCost(HeroState h) => 40 + h.Level * 12;
    public static void Experience(HeroState h, int n) { h.Xp += n; while (h.Level < Catalog.Caps[h.Rank] && h.Xp >= LevelCost(h)) { h.Xp -= LevelCost(h); h.Level++; } h.Xp = Math.Min(h.Xp, LevelCost(h)); }
    public static string? Assignment(GameState s, string id) { if (s.Encounter?.Status == "active" && s.Encounter.Team.Contains(id)) return "出战中"; if (s.Dispatch is { Paused: false } && s.Dispatch.Team.Contains(id)) return "委托中"; return s.Workers.FirstOrDefault(x => x.Value == id).Key; }
    public static bool Busy(GameState s, string id) => Assignment(s, id) is "出战中" or "委托中";
    public static Stats Compute(Catalog c, GameState s, string id)
    {
        var h = s.Heroes[id]; var a = c.ById[id].Attrs; double scale = (1000 + 52 * (h.Level - 1)) * (100 + 8 * h.Rank) / 100000d; var st = new Stats { Hp = Rules.Round((a[1] * 7 + a[0] * 2) * scale), Atk = Rules.Round((a[0] * 1.4 + 25) * scale), Magic = Rules.Round((a[4] * 1.4 + 25) * scale), Def = Rules.Round((a[1] * .55 + 15) * scale), Mdef = Rules.Round((a[9] * .5 + 15) * scale), Speed = a[2], Mp = a[9], Stamina = 40 + a[1] }; var sets = new Dictionary<string, int>();
        foreach (var itemId in h.Equipment.Values) { var it = s.Items.Single(x => x.Id == itemId); int p = Rules.Round(it.Power * (1 + it.Enhance * .12)); switch (it.Slot) { case "weapon": st.Atk += p; st.Magic += Rules.Round(p * .8); break; case "armor": st.Hp += p * 6; st.Def += Rules.Round(p * .5); break; case "feet": st.Speed += Rules.Round(p * .3); st.Mdef += Rules.Round(p * .4); break; case "accessory": st.Hp += p * 2; st.Magic += Rules.Round(p * .7); break; } st.Add(it.Affix.Key, it.Affix.Value); sets[it.Set] = sets.GetValueOrDefault(it.Set) + 1; }
        if (sets.GetValueOrDefault("破军") >= 2) st.Atk = Rules.Round(st.Atk * 1.15); if (sets.GetValueOrDefault("长生") >= 2) st.Hp = Rules.Round(st.Hp * 1.15); if (sets.GetValueOrDefault("玄策") >= 2) st.Magic = Rules.Round(st.Magic * 1.15); if (sets.GetValueOrDefault("流风") >= 2) st.Speed += 15;
        if (h.Skills.Contains("vigor")) st.Hp = Rules.Round(st.Hp * 1.12); if (h.Skills.Contains("focus")) st.Magic = Rules.Round(st.Magic * 1.15); return st;
    }
    public static void Validate(Catalog c, GameState s)
    {
        Rules.Require(s.Schema == 2 && s.Rules == Catalog.Version, "存档版本不兼容"); Rules.Require(s.Seed >= 0 && s.Serial >= 0 && s.LastClock >= 0, "存档时钟或身份计数损坏");
        foreach (var k in new[] { "ticket", "gold", "ore", "herb", "xp", "echo" }) Rules.Require(s.Resources.TryGetValue(k, out var n) && n >= 0 && n < 9007199254740991L, "资源账本非法");
        Rules.Require(s.Formation.Length == 6 && s.Formation.Where(x => x != null).Distinct().Count() == s.Formation.Count(x => x != null), "六人阵容重复"); Rules.Require(s.Formation.All(id => id == null || s.Heroes.ContainsKey(id)), "阵容人物不存在");
        Rules.Require(s.Mainline.Count == 96 && s.Mainline.Distinct().Count() == 96 && s.Mainline.All(c.ById.ContainsKey), "主线名册不兼容"); Rules.Require(s.Draws.Length == 4 && s.Draws.All(x => x >= 0) && s.Wishlist.Length == 4, "招募计数损坏");
        Rules.Require(s.Cleared.Distinct().Count() == s.Cleared.Count && s.Cleared.All(x => x >= 1 && x <= 120), "关卡进度非法"); Rules.Require(s.Items.Count <= 500, "装备背包越界"); var items = s.Items.Concat(s.Inbox).ToList(); Rules.Require(items.Select(x => x.Id).Distinct().Count() == items.Count, "装备身份重复");
        foreach (var it in items) ValidateItem(it);
        var equipped = new List<string>(); foreach (var (id, h) in s.Heroes) { Rules.Require(c.ById.ContainsKey(id) && h.Id == id, "人物身份损坏"); Rules.Require(h.Rank >= 0 && h.Rank < 6 && h.Level >= 1 && h.Level <= Catalog.Caps[h.Rank] && h.Xp >= 0, "成长越界"); Rules.Require(h.Skills.Count <= 3 && h.Skills.Distinct().Count() == h.Skills.Count && h.Skills.All(Catalog.PublicSkills.ContainsKey), "公共战技非法"); foreach (var type in new[] { "passive", "reaction" }) Rules.Require(h.Skills.Count(x => Catalog.PublicSkills[x].Type == type) <= 1, "公共战技类别超过上限"); foreach (var (slot, item) in h.Equipment) { Rules.Require(Catalog.Slots.Contains(slot) && s.Items.Any(x => x.Id == item && x.Slot == slot), "装备位置非法"); equipped.Add(item); } }
        Rules.Require(equipped.Distinct().Count() == equipped.Count, "装备不能多人同时持有"); foreach (var (id, n) in s.Fragments) Rules.Require(c.ById.ContainsKey(id) && n >= 0, "碎片账本非法");
        Rules.Require(s.Workers.Values.Distinct().Count() == s.Workers.Count && s.Workers.All(x => s.Buildings.ContainsKey(x.Key) && s.Heroes.ContainsKey(x.Value)), "岗位冲突"); Rules.Require(s.Buildings.All(x => c.Buildings.Any(b => b.Id == x.Key) && x.Value >= 1 && x.Value <= 3), "建筑数据非法");
        if (s.Dispatch is { } d) { Rules.Require(s.Cleared.Contains(d.Stage) && d.Team.Count > 0 && d.Team.Count <= 6 && d.Team.Distinct().Count() == d.Team.Count && d.Team.All(s.Heroes.ContainsKey), "委托凭证非法"); Rules.Require(d.CycleMs == (d.Stage % 10 == 0 ? 1800000 : 600000) && d.Elapsed >= 0 && d.Elapsed < d.CycleMs && d.Index >= 0, "委托周期非法"); if (!d.Paused) Rules.Require(s.Encounter == null && d.Team.All(x => !s.Workers.ContainsValue(x)), "委托占用冲突"); }
        if (s.Encounter is { } b) { Rules.Require(b.Stage >= 1 && b.Stage <= 120 && b.Wave >= 1 && b.Wave <= 3 && b.Round >= 0 && b.Round <= 150 && new[] { "active", "victory", "defeat" }.Contains(b.Status), "战斗数据非法"); Rules.Require(b.Team.All(s.Heroes.ContainsKey) && b.Units.Select(x => x.Id).Distinct().Count() == b.Units.Count, "战斗身份非法"); foreach (var u in b.Units) Rules.Require(Catalog.Roles.ContainsKey(u.Role) && u.Stats.Hp > 0 && u.Hp >= 0 && u.Hp <= u.Stats.Hp && u.Slot >= 0 && u.Slot < 6 && u.Side is "ally" or "enemy", "战斗单位损坏"); if (b.Status == "active") Rules.Require(b.Team.All(x => !s.Workers.ContainsValue(x)), "出战岗位冲突"); }
        if (s.Pending is { } o) { Rules.Require(o.Options.Count is > 0 and <= 3 && o.Kind is "recruit" or "loot", "待选记录非法"); if (o.Kind == "recruit") Rules.Require(o.Options.All(x => c.ById.ContainsKey(x.Id) && !c.ById[x.Id].Story && c.ById[x.Id].Region == o.Region), "剧情人物混入普通池"); else foreach (var option in o.Options) { Rules.Require(option.Item != null, "宝箱装备丢失"); ValidateItem(option.Item!); } }
    }
    private static void ValidateItem(Item it) => Rules.Require(!string.IsNullOrWhiteSpace(it.Id) && Catalog.Slots.Contains(it.Slot) && Catalog.Sets.Contains(it.Set) && it.Quality is >= 1 and <= 3 && it.Enhance is >= 0 and <= 10 && it.Level is >= 1 and <= 120 && it.Power > 0 && it.Affix.Value >= 0 && new[] { "atk", "magic", "def", "speed" }.Contains(it.Affix.Key), "装备数据非法");
}
